<p><em>Series Thumbnails Will Be Generated by Zype Plugin</em></p>

<ul class="list-series">
    <?php foreach ($categoryValues as $categoryValue): ?>
        <?php if (array_key_exists($categoryValue, $categoriesConfig)): ?>
            <?php foreach ($categoriesConfig[$categoryValue] as $item): ?>
                <?php $url = home_url($item['url']) ?>

                <li class="list-series__item">
                    <a class="list-series__link" href="<?php echo $url; ?>">
                        <div class="list-series__thumb object-fluid object-fluid--16x9">
                            <img class="lazy" src="http://lorempixel.com/400/225/people/1"
                                 alt="<?php echo $categoryValue; ?>">
                            <noscript><img src="http://lorempixel.com/400/225/people/2" alt="Season Title">
                            </noscript>
                        </div>
                        <div class="list-series__title">
                            <h3><?php echo $categoryValue; ?></h3>
                        </div>
                    </a>
                </li>
            <?php endforeach ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>